import {
  registerToolcraftRendererPipeline,
  type ToolcraftRendererPipelinePassContract,
} from "@/toolcraft/runtime";

type IsolinePipelinePasses = {
  "line-render": ToolcraftRendererPipelinePassContract<void>;
  "parametric-grid": ToolcraftRendererPipelinePassContract<void>;
  "particle-render": ToolcraftRendererPipelinePassContract<void>;
  "particle-state": ToolcraftRendererPipelinePassContract<void>;
  "physics-step": ToolcraftRendererPipelinePassContract<void>;
};

const formTargets = [
  "look.preset",
  "look.seed",
  "ring.innerRadius",
  "ring.outerRadius",
  "ring.lineCount",
  "ring.harmonicCount",
  "ring.bulgeAmount",
  "ring.bulgeAngle",
  "ring.smoothness",
  "ring.rotation",
  "space.bendX",
  "space.bendY",
  "space.depthZ",
  "view.orbit",
  "motion.flow",
  "motion.breathe",
  "motion.speed",
] as const;

const appearanceTargets = [
  "appearance.background",
  "appearance.backgroundFill",
  "appearance.backgroundGradient",
  "appearance.backgroundImage",
  "ink.gradient",
  "line.makeup",
  "line.thickness",
  "line.widthProfile",
  "line.dashLength",
  "line.dashGap",
] as const;

const physicsTargets = [
  "physics.strength",
  "physics.radius",
  "physics.waveSpeed",
  "physics.damping",
  "physics.return",
  "particles.size",
  "particles.spread",
  "particles.scatter",
  "particles.return",
  "particles.damping",
] as const;

export const isolineRendererPipeline =
  registerToolcraftRendererPipeline<IsolinePipelinePasses>()({
    interactionInvalidation: [
      {
        interaction: "initial-render",
        invalidates: [
          "parametric-grid",
          "particle-state",
          "physics-step",
          "line-render",
          "particle-render",
        ],
        targets: ["canvas.initial-render"],
      },
      {
        interaction: "animation-frame",
        invalidates: ["physics-step", "line-render", "particle-render"],
        mustNotInvalidate: ["parametric-grid", "particle-state"],
        targets: ["runtime.animation-frame"],
      },
      {
        interaction: "control-drag",
        invalidates: ["line-render", "physics-step", "particle-render"],
        mustNotInvalidate: ["parametric-grid", "particle-state"],
        targets: [
          "ring.innerRadius",
          "ring.outerRadius",
          "ring.harmonicCount",
          "ring.bulgeAmount",
          "ring.bulgeAngle",
          "ring.smoothness",
          "ring.rotation",
          "look.seed",
          "space.bendX",
          "space.bendY",
          "space.depthZ",
          "line.thickness",
          "line.dashLength",
          "line.dashGap",
          ...physicsTargets,
          "motion.speed",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["parametric-grid", "line-render"],
        mustNotInvalidate: ["particle-state"],
        targets: ["ring.lineCount"],
      },
      {
        interaction: "control-drag",
        invalidates: ["particle-state", "physics-step", "particle-render"],
        mustNotInvalidate: ["parametric-grid"],
        targets: ["particles.count"],
      },
      {
        interaction: "control-change",
        invalidates: ["line-render", "physics-step", "particle-render"],
        mustNotInvalidate: ["parametric-grid", "particle-state"],
        targets: [
          ...formTargets,
          ...appearanceTargets,
          ...physicsTargets,
        ],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: [
          "parametric-grid",
          "particle-state",
          "physics-step",
          "line-render",
          "particle-render",
        ],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: [
          "parametric-grid",
          "particle-state",
          "physics-step",
          "line-render",
          "particle-render",
        ],
        targets: ["canvas.viewport"],
      },
    ],
    passes: [
      {
        cacheKey: ["ring.lineCount", "renderer.angular-samples"],
        cost: {
          dimensions: ["line-count"],
          frequency: "discrete",
          relationship: "linear",
        },
        id: "parametric-grid",
        inputs: ["ring.lineCount", "renderer.angular-samples"],
        invalidatedBy: ["ring.lineCount"],
        kind: "vector-build",
        lifecycle: { cache: "memoized", resourceScope: "renderer" },
        output: "intermediate",
        quality: "full",
        runsOn: "gpu",
      },
      {
        cacheKey: ["particles.count", "look.seed"],
        cost: {
          dimensions: ["particle-count"],
          frequency: "discrete",
          relationship: "linear",
        },
        id: "particle-state",
        inputs: ["particles.count", "look.seed"],
        invalidatedBy: ["particles.count", "look.seed"],
        kind: "preprocess",
        lifecycle: { cache: "memoized", resourceScope: "renderer" },
        output: "intermediate",
        quality: "full",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "particle-state",
          "interaction.impulses",
          ...physicsTargets,
        ],
        cost: {
          dimensions: ["particle-count"],
          frequency: "frame",
          relationship: "linear",
        },
        id: "physics-step",
        inputs: ["particle-state", ...physicsTargets, "interaction.impulses"],
        invalidatedBy: [
          "runtime.animation-frame",
          "interaction.impulses",
          ...physicsTargets,
        ],
        kind: "vector-build",
        lifecycle: { cache: "memoized", resourceScope: "renderer" },
        output: "intermediate",
        quality: "full",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "parametric-grid",
          ...formTargets,
          ...appearanceTargets,
          ...physicsTargets,
          "interaction.impulses",
          "runtime.animation-frame",
          "canvas.renderScale",
        ],
        cost: {
          dimensions: ["line-count"],
          frequency: "frame",
          relationship: "linear",
        },
        id: "line-render",
        inputs: [
          "parametric-grid",
          ...formTargets,
          ...appearanceTargets,
          ...physicsTargets,
          "interaction.impulses",
          "runtime.animation-frame",
          "canvas.renderScale",
        ],
        invalidatedBy: [
          "parametric-grid",
          ...formTargets,
          ...appearanceTargets,
          ...physicsTargets,
          "interaction.impulses",
          "runtime.animation-frame",
          "canvas.renderScale",
        ],
        kind: "composite",
        lifecycle: { cache: "memoized", resourceScope: "renderer" },
        output: "preview",
        quality: "retina",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "physics-step",
          ...formTargets,
          ...appearanceTargets,
          "particles.size",
          "runtime.animation-frame",
          "canvas.renderScale",
        ],
        cost: {
          dimensions: ["particle-count"],
          frequency: "frame",
          relationship: "linear",
        },
        id: "particle-render",
        inputs: [
          "physics-step",
          ...formTargets,
          ...appearanceTargets,
          "particles.size",
          "runtime.animation-frame",
          "canvas.renderScale",
        ],
        invalidatedBy: [
          "physics-step",
          ...formTargets,
          ...appearanceTargets,
          "particles.size",
          "runtime.animation-frame",
          "canvas.renderScale",
        ],
        kind: "composite",
        lifecycle: { cache: "memoized", resourceScope: "renderer" },
        output: "preview",
        quality: "retina",
        runsOn: "gpu",
      },
    ],
    runtimeId: "intermission-isoline-webgl-v1",
  });
