import {
  ISOLINE_BACKGROUND_FILL_TARGET,
  ISOLINE_BACKGROUND_IMAGE_TARGET,
  ISOLINE_LINE_COUNT_DEFAULT,
  ISOLINE_LINE_COUNT_MAX,
  ISOLINE_LINE_COUNT_MIN,
  ISOLINE_PARTICLE_COUNT_DEFAULT,
  ISOLINE_PARTICLE_COUNT_MAX,
  ISOLINE_PARTICLE_COUNT_MIN,
  ISOLINE_SEED_DEFAULT,
  ISOLINE_SEED_MAX,
  ISOLINE_SEED_MIN,
} from "./constants";
import {
  isolineBackgroundGradientDefault,
  isolineGradientDefault,
  isolineOrientationDefault,
  isolineReferenceValues,
  isolineWidthProfileDefault,
} from "./presets";

const always = { mode: "always" as const };

const gradientFillOnly = {
  all: [{ equals: "gradient", target: ISOLINE_BACKGROUND_FILL_TARGET }],
  mode: "conditional" as const,
};

const imageFillOnly = {
  all: [{ equals: "image", target: ISOLINE_BACKGROUND_FILL_TARGET }],
  mode: "conditional" as const,
};

export const isolineBackgroundSection = {
  controls: {
    includeBackground: {
      applicability: always,
      defaultValue: true,
      description: "Shows the field behind the interactive line object.",
      label: "Include",
      performanceReason: "Toggles whether preview fills the field.",
      performanceRole: "responsiveness" as const,
      target: "export.includeBackground",
      type: "switch" as const,
    },
    backgroundFill: {
      applicability: always,
      defaultValue: isolineReferenceValues.backgroundFill,
      label: "Type",
      options: [
        { label: "Solid", value: "solid" },
        { label: "Gradient", value: "gradient" },
        { label: "Image", value: "image" },
      ],
      performanceReason: "Selects the field fill path.",
      performanceRole: "responsiveness" as const,
      target: ISOLINE_BACKGROUND_FILL_TARGET,
      type: "segmented" as const,
    },
    background: {
      applicability: always,
      defaultValue: isolineReferenceValues.background,
      label: false,
      performanceReason: "Changes the field fill color.",
      performanceRole: "responsiveness" as const,
      target: "appearance.background",
      type: "color" as const,
    },
    backgroundGradient: {
      applicability: gradientFillOnly,
      defaultValue: isolineBackgroundGradientDefault,
      label: false,
      performanceReason: "Updates the screen-space field gradient uniforms.",
      performanceRole: "responsiveness" as const,
      target: "appearance.backgroundGradient",
      type: "gradient" as const,
    },
    backgroundImage: {
      applicability: imageFillOnly,
      assetKind: "image" as const,
      defaultValue: null,
      hardMaxItems: 1,
      label: false,
      performanceReason: "Uploads a cover image that replaces the field fill.",
      performanceRole: "responsiveness" as const,
      target: ISOLINE_BACKGROUND_IMAGE_TARGET,
      type: "fileDrop" as const,
    },
  },
  id: "background",
  title: "Background",
};

export const isolineLookSection = {
  controls: {
    preset: {
      applicability: always,
      defaultValue: isolineReferenceValues.look,
      description: "Applies a complete look from the same isoline family.",
      label: "Preset",
      options: [
        { label: "Reference", value: "reference" },
        { label: "Quiet", value: "quiet" },
        { label: "Drift", value: "drift" },
        { label: "Dense", value: "dense" },
        { label: "Inverse", value: "inverse" },
      ],
      performanceReason: "Swaps a small set of silhouette and color values.",
      performanceRole: "responsiveness" as const,
      target: "look.preset",
      type: "select" as const,
    },
  },
  id: "look",
  title: "Look",
};

export const isolineSeedSection = {
  controls: {
    seed: {
      applicability: always,
      defaultValue: ISOLINE_SEED_DEFAULT,
      description: "Keeps the same language while shifting harmonic phases.",
      label: "Seed",
      max: ISOLINE_SEED_MAX,
      min: ISOLINE_SEED_MIN,
      performanceReason: "Rebuilds isoline phases from a new random offset.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 1,
      target: "look.seed",
      type: "slider" as const,
    },
    randomize: {
      actions: [{ label: "Randomize", value: "randomize-seed" }],
      applicability: always,
      label: "New seed",
      performanceReason: "Writes a new seed and rebuilds isoline phases.",
      performanceRole: "responsiveness" as const,
      target: "look.randomize",
      type: "actions" as const,
    },
  },
  id: "seed",
  title: "Variation",
};

export const isolineRingSection = {
  controls: {
    innerRadius: {
      applicability: always,
      defaultValue: isolineReferenceValues.innerRadius,
      label: "Inner",
      max: 0.7,
      min: 0.08,
      performanceReason: "Changes hole size and rebuilds every isoline.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "silhouette",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "ring.innerRadius",
      type: "slider" as const,
    },
    outerRadius: {
      applicability: always,
      defaultValue: isolineReferenceValues.outerRadius,
      label: "Outer",
      max: 0.9,
      min: 0.16,
      performanceReason: "Changes ring width and rebuilds every isoline.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "silhouette",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "ring.outerRadius",
      type: "slider" as const,
    },
    rotation: {
      applicability: always,
      defaultValue: isolineReferenceValues.rotation,
      label: "Turn",
      max: 360,
      min: 0,
      performanceReason: "Rotates the shared silhouette.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "silhouette",
      sliderValueKind: "continuous" as const,
      step: 1,
      target: "ring.rotation",
      type: "slider" as const,
      unit: "°",
    },
    lineCount: {
      applicability: always,
      defaultValue: ISOLINE_LINE_COUNT_DEFAULT,
      description: "Number of closed contour steps between the hole and the outer edge.",
      label: "Lines",
      max: ISOLINE_LINE_COUNT_MAX,
      min: ISOLINE_LINE_COUNT_MIN,
      performanceReason: "Each added isoline is another stroked closed path.",
      performanceRole: "workload" as const,
      semanticGroup: "isolines",
      sliderValueKind: "continuous" as const,
      step: 1,
      target: "ring.lineCount",
      type: "slider" as const,
    },
    harmonicCount: {
      applicability: always,
      defaultValue: isolineReferenceValues.harmonicCount,
      label: "Harmonics",
      max: 6,
      min: 1,
      performanceReason: "Adds angular frequencies to the shared deformation.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "deform",
      markerCount: 6,
      sliderValueKind: "discrete" as const,
      step: 1,
      target: "ring.harmonicCount",
      type: "slider" as const,
      variant: "discrete" as const,
    },
    bulgeAmount: {
      applicability: always,
      defaultValue: isolineReferenceValues.bulgeAmount,
      label: "Bulge",
      max: 0.45,
      min: 0,
      performanceReason: "Scales the shared harmonic deformation.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "deform",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "ring.bulgeAmount",
      type: "slider" as const,
    },
    bulgeAngle: {
      applicability: always,
      defaultValue: isolineReferenceValues.bulgeAngle,
      label: "Angle",
      max: 360,
      min: 0,
      performanceReason: "Aims the primary bulge around the ring.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "deform",
      sliderValueKind: "continuous" as const,
      step: 1,
      target: "ring.bulgeAngle",
      type: "slider" as const,
      unit: "°",
    },
    smoothness: {
      applicability: always,
      defaultValue: isolineReferenceValues.smoothness,
      label: "Smooth",
      max: 1,
      min: 0,
      performanceReason: "Blends harmonic regularity against residual noise.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "deform",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "ring.smoothness",
      type: "slider" as const,
    },
  },
  id: "ring",
  title: "Ring",
};

export const isolineMotionSection = {
  controls: {
    flow: {
      applicability: always,
      defaultValue: isolineReferenceValues.flow,
      description: "Moves phase through the lines without rotating the object.",
      label: "Flow",
      performanceReason: "Adds continuous phase travel in the vertex shader.",
      performanceRole: "responsiveness" as const,
      target: "motion.flow",
      type: "switch" as const,
    },
    breathe: {
      applicability: always,
      defaultValue: isolineReferenceValues.breathe,
      description: "Scales the ring in and out continuously.",
      label: "Breathe",
      performanceReason: "Adds a continuous scale pulse to isoline rebuilds.",
      performanceRole: "responsiveness" as const,
      target: "motion.breathe",
      type: "switch" as const,
    },
  },
  id: "motion",
  layoutGroups: [
    {
      columns: 2 as const,
      controls: ["flow", "breathe"],
      layout: "inline" as const,
    },
  ],
  title: "Motion",
};

export const isolineTempoSection = {
  controls: {
    speed: {
      applicability: always,
      defaultValue: isolineReferenceValues.speed,
      label: "Speed",
      max: 2,
      min: 0,
      performanceReason: "Changes how quickly continuous flow and breathe travel.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.05,
      target: "motion.speed",
      type: "slider" as const,
    },
  },
  id: "tempo",
  title: "Tempo",
};

export const isolineInkSection = {
  controls: {
    gradient: {
      applicability: always,
      defaultValue: isolineGradientDefault,
      label: false,
      performanceReason: "Updates line color stops and gradient projection uniforms.",
      performanceRole: "responsiveness" as const,
      target: "ink.gradient",
      type: "gradient" as const,
    },
  },
  id: "ink",
  title: "Ink",
};

export const isolineSpaceSection = {
  controls: {
    bendX: {
      applicability: always,
      defaultValue: isolineReferenceValues.bendX,
      label: "X bend",
      max: 1,
      min: -1,
      performanceReason: "Updates X-axis vertex deformation.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "space.bendX",
      type: "slider" as const,
    },
    bendY: {
      applicability: always,
      defaultValue: isolineReferenceValues.bendY,
      label: "Y bend",
      max: 1,
      min: -1,
      performanceReason: "Updates Y-axis vertex deformation.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "space.bendY",
      type: "slider" as const,
    },
    depthZ: {
      applicability: always,
      defaultValue: isolineReferenceValues.depthZ,
      label: "Z depth",
      max: 1.5,
      min: 0,
      performanceReason: "Updates Z-axis vertex deformation.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "space.depthZ",
      type: "slider" as const,
    },
    orientation: {
      applicability: always,
      defaultValue: isolineOrientationDefault,
      keyframeable: false,
      label: false,
      performanceReason: "Updates the retained camera pose uniform.",
      performanceRole: "responsiveness" as const,
      target: "view.orbit",
      type: "orientationGizmo" as const,
    },
  },
  id: "space",
  title: "Space",
};

const dashedOnly = {
  all: [{ equals: "dashed", target: "line.makeup" }],
  mode: "conditional" as const,
};

const particlesOnly = {
  all: [{ equals: "particles", target: "line.makeup" }],
  mode: "conditional" as const,
};

export const isolineLineSection = {
  controls: {
    makeup: {
      applicability: always,
      defaultValue: isolineReferenceValues.lineMode,
      label: "Makeup",
      options: [
        { label: "Solid", value: "solid" },
        { label: "Dashed", value: "dashed" },
        { label: "Particles", value: "particles" },
      ],
      performanceReason: "Selects the line or particle render pass.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "mode",
      target: "line.makeup",
      type: "segmented" as const,
    },
    thickness: {
      applicability: always,
      defaultValue: isolineReferenceValues.lineThickness,
      label: "Thickness",
      max: 8,
      min: 0.2,
      performanceReason: "Updates inner and outer strip widths.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "width",
      sliderValueKind: "continuous" as const,
      step: 0.05,
      target: "line.thickness",
      type: "rangeSlider" as const,
      unit: "px",
    },
    dashLength: {
      applicability: dashedOnly,
      defaultValue: isolineReferenceValues.dashLength,
      label: "Dash",
      max: 0.3,
      min: 0.01,
      performanceReason: "Updates the dashed fragment mask.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "dash",
      sliderValueKind: "continuous" as const,
      step: 0.005,
      target: "line.dashLength",
      type: "slider" as const,
    },
    dashGap: {
      applicability: dashedOnly,
      defaultValue: isolineReferenceValues.dashGap,
      label: "Gap",
      max: 0.2,
      min: 0.005,
      performanceReason: "Updates the dashed fragment mask.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "dash",
      sliderValueKind: "continuous" as const,
      step: 0.005,
      target: "line.dashGap",
      type: "slider" as const,
    },
    particleCount: {
      applicability: particlesOnly,
      defaultValue: ISOLINE_PARTICLE_COUNT_DEFAULT,
      label: "Particles count",
      max: ISOLINE_PARTICLE_COUNT_MAX,
      min: ISOLINE_PARTICLE_COUNT_MIN,
      performanceReason: "Controls transform-feedback particle workload.",
      performanceRole: "workload" as const,
      semanticGroup: "particles",
      sliderValueKind: "continuous" as const,
      step: 100,
      target: "particles.count",
      type: "slider" as const,
    },
    particleSize: {
      applicability: particlesOnly,
      defaultValue: isolineReferenceValues.particleSize,
      label: "Particles size",
      max: 8,
      min: 0.5,
      performanceReason: "Updates rendered particle point size.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "particles",
      sliderValueKind: "continuous" as const,
      step: 0.1,
      target: "particles.size",
      type: "slider" as const,
      unit: "px",
    },
    particleSpread: {
      applicability: particlesOnly,
      defaultValue: isolineReferenceValues.particleSpread,
      label: "Spread",
      max: 1,
      min: 0,
      performanceReason: "Updates deterministic particle offsets from their home lines.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "particles",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "particles.spread",
      type: "slider" as const,
    },
    particleScatter: {
      applicability: particlesOnly,
      defaultValue: isolineReferenceValues.particleScatter,
      label: "Scatter",
      max: 2,
      min: 0,
      performanceReason: "Updates impulse force applied to particle state.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "particles",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "particles.scatter",
      type: "slider" as const,
    },
    particleReturn: {
      applicability: particlesOnly,
      defaultValue: isolineReferenceValues.particleReturn,
      label: "Return",
      max: 1,
      min: 0.01,
      performanceReason: "Updates the particle spring-to-home coefficient.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "particles",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "particles.return",
      type: "slider" as const,
    },
    particleDamping: {
      applicability: particlesOnly,
      defaultValue: isolineReferenceValues.particleDamping,
      label: "Damping",
      max: 0.99,
      min: 0.5,
      performanceReason: "Updates particle velocity decay.",
      performanceRole: "responsiveness" as const,
      semanticGroup: "particles",
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "particles.damping",
      type: "slider" as const,
    },
  },
  id: "line",
  title: "Line",
};

export const isolineWidthProfileSection = {
  controls: {
    widthProfile: {
      applicability: always,
      curveIntent: "single-value-map" as const,
      defaultValue: isolineWidthProfileDefault,
      interpolation: "monotone" as const,
      label: false,
      performanceReason: "Updates the radial strip-width lookup.",
      performanceRole: "responsiveness" as const,
      target: "line.widthProfile",
      type: "curves" as const,
      variant: "single" as const,
    },
  },
  id: "width-profile",
  title: "Width Profile",
};

export const isolinePhysicsSection = {
  controls: {
    strength: {
      applicability: always,
      defaultValue: isolineReferenceValues.strumStrength,
      label: "Strength",
      max: 2,
      min: 0,
      performanceReason: "Updates strum impulse amplitude.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "physics.strength",
      type: "slider" as const,
    },
    radius: {
      applicability: always,
      defaultValue: isolineReferenceValues.strumRadius,
      label: "Radius",
      max: 1,
      min: 0.03,
      performanceReason: "Updates strum spatial falloff.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "physics.radius",
      type: "slider" as const,
    },
    waveSpeed: {
      applicability: always,
      defaultValue: isolineReferenceValues.strumWaveSpeed,
      label: "Wave speed",
      max: 4,
      min: 0.1,
      performanceReason: "Updates impulse propagation through ring radii.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.05,
      target: "physics.waveSpeed",
      type: "slider" as const,
    },
    damping: {
      applicability: always,
      defaultValue: isolineReferenceValues.strumDamping,
      label: "Damping",
      max: 0.99,
      min: 0.5,
      performanceReason: "Updates analytical wave decay.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "physics.damping",
      type: "slider" as const,
    },
    return: {
      applicability: always,
      defaultValue: isolineReferenceValues.strumReturn,
      label: "Return",
      max: 1,
      min: 0.01,
      performanceReason: "Updates the line return spring.",
      performanceRole: "responsiveness" as const,
      sliderValueKind: "continuous" as const,
      step: 0.01,
      target: "physics.return",
      type: "slider" as const,
    },
  },
  id: "physics",
  title: "Physics",
};
